markdown: redcarpet
highlighter: pygments
permalink: pretty

breweries:
  - name: The Brewer's Art
    streetAddress: 1701 Bolton St
    city: Baltimore
    state: MD
    zip: 21217
    homepageURL: http://thebrewersart.com
    email: yo@thebrewersart.com
    phone: 410-987-8765
    lat: 
    long: 
    avatarURL: 
  - name: Wild Dog
    streetAddress: 1701 Bolton St
    city: Baltimore
    state: MD
    zip: 21217
    homepageURL: http://thebrewersart.com
    email: yo@thebrewersart.com
    phone: 410-987-8765
    lat: 
    long: 
    avatarURL: 